version: '3.7'
services:
  web:
    build: ./web
    ports:
      - "80:5000"
    environment:
      - INDEX_NAME
      - INDEX_BERT_NAME
      - DEFUSR
      - BERTADM
      - SEARCH_SIZE
      - KICKOFF_URL
      - BERT_ENDPOINT
      - ES_ENDPOINT
    depends_on:
      - elasticsearch
      - bertserving
    networks:
      - frontend
      - backend
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - backend
    tty: true
    environment:
      discovery.type: single-node

  bertserving:
    build: ./bertserving
    ports:
      - "5555:5555"
      - "5556:5556"
    environment:
      - PATH_MODEL=${PATH_MODEL}
    volumes:
      - "${PATH_MODEL}:/model"
    networks:
      - backend
      
  scrapyd:
    build: ./bertelscrapyd
    ports:
      - "6800:6800"
    environment:
      - INDEX_NAME
      - INDEX_BERT_NAME
      - BOT_NAME
      - USER_AGENT
      - BERT_ENDPOINT
      - ES_ENDPOINT
    volumes:
      - ./scrapydata:/var/lib/scrapyd
      - /usr/local/lib/python3.7/dist-packages
    restart: unless-stopped
    networks:
      - backend

  scrapy:
    image: vimagick/scrapyd:py3
    command: bash
    volumes:
      - ./scrapybatch:/code
    working_dir: /code
    restart: unless-stopped
    networks:
      - backend
      
networks:
  frontend:
  backend:
volumes:
  es-data:
    driver: local
