apiVersion: apps/v1
kind: Deployment
metadata:
  name: bert-elasticsearch
  labels:
    name: bert-elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bert-elasticsearch
  template:
    metadata:
      labels:
        app: bert-elasticsearch
    spec:
      containers:
      - image: launcher.gcr.io/google/elasticsearch7
        name: elasticsearch
        ports:
        - containerPort: 9200
        volumeMounts:
        - name: elasticsearchdata
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: elasticsearchdata
        persistentVolumeClaim:
          claimName: elasticsearchdata
---
# Request a clusterip internal service.
apiVersion: v1
kind: Service
metadata:
  name: bert-elasticsearch-service
spec:
  selector:
    app: bert-elasticsearch
  type: ClusterIP
  ports:
  - name: elasticsearchport
    protocol: TCP
    port: 9200
    targetPort: 9200
---
# Request a persistent volume from the cluster using a Persistent Volume Claim.
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elasticsearchdata
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
